name: Update Zone 5 Gists

on:
  push:
    branches: [ main ]
    paths:
      - 'workouts/**.csv'
      - '.github/**'

jobs:
  update-gists:
    name: Update Zone 5 Gists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install dependencies
        run: gem install octokit
        
      - name: Update summary gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          ruby .github/scripts/hadge.rb -t $GH_TOKEN -g $GIST_ID workouts/2025.csv
          
      - name: Update contribution graph gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID_CONTRIBUTION: ${{ secrets.GIST_ID_CONTRIBUTION }}
        run: |
          ruby .github/scripts/zone5-contribution-graph.rb -t $GH_TOKEN -g $GIST_ID_CONTRIBUTION workouts/2025.csv 